### PR TITLE
Improved auto() function and other changes

### PR DESCRIPTION
**Pull request by Seniru**
Improvements in auto() function
 - Changed the checking for binary to a regex check. In previous 
versions auto() function identified "0100fdsfd0101" as a binary value. 
In this commit I fixed that bug.

Other improvements
 - Added common-js as a dependency
 - Added node-modules to .gitignore file
 - Separated npm and CI badge in READMe with double new lines (because 
in previous versions it displayed in the same line)

### CODE REVIEW

**Comment by ChickenNaggetGitHub** [comment]
Thank you!!!

**Comment by Seniru** [comment]
Welcome and thanks for merging😀

**Comment by ChickenNaggetGitHub** [comment]
But why did you add common-js as dependency? @Seniru

**Comment by Seniru** [comment]
Because you have module.exports in your code.

**Comment by ChickenNaggetGitHub** [comment]
Oh Ok

**Comment by ChickenNaggetGitHub** [comment]
but dont i need to require / set it up or something?

**Comment by Seniru** [comment]
> but dont i need to require / set it up or something? @Seniru

What, I didn't get u?

**Comment by ChickenNaggetGitHub** [comment]
that module

**Comment by Seniru** [comment]
Which module? I can't understand what are you talking @ChickenNaggetGitHub . Can you describe more :)

**Comment by ChickenNaggetGitHub** [comment]
So.. you installed common-js as dependency aand im asking if i dont need to at least "require()" it or somehow set it up

**Comment by Seniru** [comment]
Node js environments don't need common js as it spotty those functionalities automatically.  Therefore you don't need to reqire in your code.  I added or as a dependency for non node users. You can remove it if you wish

**Comment by ChickenNaggetGitHub** [comment]
Oh okay @Seniru

**Pull request merged**
